name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 20
      - run: npm i
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint --parallel

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t test --parallel

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t build --parallel

  # e2e:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/cache-restore
  #       id: cache-node-modules
  #       with:
  #         node-version: 20
  #     - uses: nrwl/nx-set-shas@v4
  #     - run: npx nx affected -t e2e --parallel
